# Part of the redesigned client management system
# Makes sure packages are installed on the client
---
- name: Install packages on Debian/Ubuntu
  hosts: wrong_host_fallback
  gather_facts: no
  become: yes
  vars:
    packages_default:
      - git
      - python3-venv
      - build-essential
      - libuhd-dev
      - python3-uhd
      - uhd-host
      - cmake
      - libboost-all-dev

    packages_to_install: "{{ packages_default + (extra_packages | default([])) }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # in seconds

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages_to_install }}"
        state: present
        install_recommends: no
