# Part of the redesigned client management system
# Makes sure packages are installed on the client
---
- name: Install packages on Debian/Ubuntu
  hosts: all
  become: yes
  vars:
    packages_to_install:
      - git
      - python3-venv
      - build-essential
      - libuhd-dev
      - python3-uhd
      - uhd-host
      - cmake
      - libboost-all-dev
      - python3-scipy
      - python3-zmq

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # in seconds

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages_to_install }}"
        state: present
        install_recommends: no
